export const SET_CURRENT_BREAKPOINTS = 'SET_CURRENT_BREAKPOINTS';

export const RESET_SEARCH_VAL = 'RESET_SEARCH_VAL';
export const SET_SEARCH_VAL = 'SET_SEARCH_VAL';

export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTISTS_SUCCES = 'GET_ARTISTS_SUCCES';
export const GET_ARTISTS_FAILED = 'GET_ARTISTS_FAILED';
export const SET_ACTIVE_ARTIST = 'SET_ACTIVE_ARTIST';

export const TOGGLE_BURGER = 'TOGGLE_BURGER';

